"""
Pydantic models for health surveillance agents - DabDar v4.0
Extended schema with epidemiological triad analysis and bilingual support

v4.0 Changes:
- VALID_SOURCES now dynamically loaded from source_registry
- Single source of truth for all source configuration
"""

from pydantic import BaseModel, Field
from datetime import datetime
from typing import Optional, List, Literal
from enum import Enum


class Priority(str, Enum):
    """Finding priority levels"""

    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class SourceType(str, Enum):
    """Data source types"""

    CHANGEDETECTION = "changedetection"
    RSS = "rss"
    RSSHUB = "rsshub"
    GOOGLE_SEARCH = "google_search"
    MANUAL = "manual"


# DabDar v4.0: VALID_SOURCES now loaded dynamically from source registry
# Lazy import to avoid circular dependency
def _get_valid_sources() -> List[str]:
    """Get valid sources from source registry."""
    try:
        from health_agents.shared.source_registry import get_valid_sources

        return get_valid_sources()
    except Exception as e:
        print(f"⚠️  Failed to load from source registry: {e}")
        # Fallback to hardcoded list
        return [
            "WHO",
            "CDC",
            "PROMED",
            "WHO_RSS",
            "CDC_RSS",
            "GOOGLE",
            "WHO_CLONE",
        ]


# Backward compatibility: VALID_SOURCES as property
VALID_SOURCES = _get_valid_sources()


class Finding(BaseModel):
    """
    DabDar v3.0 Finding schema with epidemiological triad and bilingual support
    """

    # Core identifiers
    id: Optional[int] = None  # Auto-generated by NocoDB

    # Disease identification
    disease: str = Field(
        ..., description="Primary disease name (e.g., Mpox, Marburg, MERS)"
    )

    # Source information
    source: str = Field(
        ..., description="Source name (WHO, CDC, WHO_RSS, GOOGLE, etc.)"
    )
    source_type: Optional[SourceType] = Field(
        default=SourceType.CHANGEDETECTION, description="Type of data source"
    )
    source_link: str = Field(default="", description="Original source URL")

    # Dates
    publication_date: Optional[str] = Field(
        default=None, description="Publication date in YYYY-MM-DD format"
    )
    detected_at: Optional[str] = Field(
        default=None, description="When this finding was detected by the system"
    )

    # Content - English
    headline: str = Field(..., description="Main finding headline")
    short_description_en: str = Field(
        default="",
        description="1-2 sentence epidemiological triad summary (WHO/WHERE/WHEN)",
    )
    detailed_description_en: str = Field(
        default="", description="3-5 paragraph detailed epidemiological analysis"
    )

    # Content - Arabic (translated)
    short_description_ar: str = Field(
        default="", description="Arabic translation of short description"
    )
    detailed_description_ar: str = Field(
        default="", description="Arabic translation of detailed description"
    )

    # Deduplication
    content_hash: Optional[str] = Field(
        default=None, description="SHA-256 hash for deduplication"
    )

    # Status tracking
    priority: Priority = Field(
        default=Priority.MEDIUM, description="Finding priority level"
    )
    risk: Optional[str] = Field(
        default=None,
        description="Normalized outbreak risk. Falls back to legacy priority when omitted.",
    )
    risk_assessment: str = Field(
        default="",
        description="Free-text risk assessment. When present, it overrides the normalized risk label in the globe UI.",
    )
    notification_sent: bool = Field(
        default=False,
        description="Whether this finding has been included in an email digest",
    )

    # Legacy fields (kept for backward compatibility)
    agency: Optional[str] = Field(
        default=None, description="Legacy: Maps to 'source' field"
    )
    summary: Optional[str] = Field(
        default=None, description="Legacy: Maps to 'short_description_en'"
    )
    url: Optional[str] = Field(
        default=None, description="Legacy: Maps to 'source_link'"
    )

    def to_legacy_dict(self) -> dict:
        """Convert to legacy format for backward compatibility"""
        return {
            "date": self.publication_date or datetime.now().strftime("%Y-%m-%d"),
            "agency": self.source,
            "headline": self.headline,
            "summary": self.short_description_en or self.summary or "",
            "url": self.source_link or self.url or "",
        }

    def to_v3_dict(self) -> dict:
        """Convert to full v3 format for NocoDB"""
        return {
            "disease": self.disease,
            "source": self.source,
            "source_type": self.source_type.value
            if self.source_type
            else "changedetection",
            "source_link": self.source_link or self.url or "",
            "publication_date": self.publication_date
            or datetime.now().strftime("%Y-%m-%d"),
            "headline": self.headline,
            "short_description_en": self.short_description_en or self.summary or "",
            "detailed_description_en": self.detailed_description_en,
            "short_description_ar": self.short_description_ar,
            "detailed_description_ar": self.detailed_description_ar,
            "content_hash": self.content_hash,
            "risk": self.risk or self.priority.value
            if isinstance(self.priority, Priority)
            else self.priority,
            "risk_assessment": self.risk_assessment,
            "notification_sent": self.notification_sent,
        }


class EpidemiologicalTriad(BaseModel):
    """WHO/WHERE/WHEN extraction structure"""

    # WHO - Affected population
    who_affected: str = Field(
        default="",
        description="Description of affected population (demographics, numbers)",
    )
    cases_confirmed: Optional[int] = Field(
        default=None, description="Number of confirmed cases"
    )
    cases_suspected: Optional[int] = Field(
        default=None, description="Number of suspected cases"
    )
    deaths: Optional[int] = Field(default=None, description="Number of deaths")
    mortality_rate: Optional[float] = Field(
        default=None, description="Case fatality rate if known"
    )

    # WHERE - Geographic location
    where_location: str = Field(
        default="", description="Geographic location(s) of the outbreak"
    )
    countries: List[str] = Field(
        default_factory=list, description="List of affected countries"
    )
    regions: List[str] = Field(
        default_factory=list, description="List of affected regions"
    )

    # WHEN - Time period
    when_period: str = Field(
        default="", description="Time period of the outbreak/report"
    )
    start_date: Optional[str] = Field(
        default=None, description="Outbreak start date if known"
    )
    end_date: Optional[str] = Field(
        default=None, description="Outbreak end date or 'ongoing'"
    )

    # Additional context
    interventions: List[str] = Field(
        default_factory=list, description="Response measures and interventions"
    )
    risk_assessment: str = Field(default="", description="Risk assessment summary")


class Disease(BaseModel):
    """Disease configuration model"""

    name: str = Field(..., description="Primary disease name")
    aliases: List[str] = Field(default_factory=list, description="Alternative names")
    arabic_name: str = Field(default="", description="Arabic name of disease")
    keywords_en: List[str] = Field(
        default_factory=list, description="English search keywords"
    )
    keywords_ar: List[str] = Field(
        default_factory=list, description="Arabic search keywords"
    )
    priority: Priority = Field(default=Priority.MEDIUM, description="Default priority")
    who_classification: str = Field(default="", description="WHO classification")


class DigestReport(BaseModel):
    """Email digest compilation model"""

    digest_id: str = Field(..., description="Unique digest identifier")
    period: Literal["hourly", "6hours", "daily"] = Field(
        default="daily", description="Digest period type"
    )
    period_start: str = Field(..., description="Start of digest period (ISO format)")
    period_end: str = Field(..., description="End of digest period (ISO format)")

    # Statistics
    total_findings: int = Field(default=0, description="Total findings in this digest")
    critical_count: int = Field(default=0, description="Number of critical findings")
    high_count: int = Field(default=0, description="Number of high priority findings")
    medium_count: int = Field(
        default=0, description="Number of medium priority findings"
    )
    low_count: int = Field(default=0, description="Number of low priority findings")

    # Content
    findings: List[Finding] = Field(
        default_factory=list, description="Findings in this digest"
    )
    html_content_en: str = Field(
        default="", description="HTML formatted English content"
    )
    html_content_ar: str = Field(
        default="", description="HTML formatted Arabic content"
    )

    # Delivery status
    sent_at: Optional[str] = Field(default=None, description="When digest was sent")
    recipients: List[str] = Field(default_factory=list, description="Email recipients")
    delivery_status: str = Field(default="pending", description="Delivery status")


class RSSItem(BaseModel):
    """RSS feed item model"""

    title: str = Field(..., description="Article title")
    link: str = Field(..., description="Article URL")
    published_date: str = Field(..., description="Publication date")
    description: str = Field(default="", description="Article description/summary")
    source: str = Field(..., description="RSS feed source name")
    guid: Optional[str] = Field(default=None, description="Unique identifier")


class GoogleSearchResult(BaseModel):
    """Google Custom Search result model"""

    title: str = Field(..., description="Result title")
    link: str = Field(..., description="Result URL")
    snippet: str = Field(default="", description="Result snippet")
    source: str = Field(default="GOOGLE", description="Source identifier")
    language: str = Field(default="en", description="Search language")
    disease: str = Field(..., description="Disease searched for")


class Report(BaseModel):
    """Daily report model"""

    report_date: str
    narrative: str = Field(..., description="AI-generated executive summary")
    findings_count: int
    agencies_active: List[str]


class AgencyConfig(BaseModel):
    """Agency/Source configuration"""

    name: str
    watch_id: str = Field(default="")
    url_pattern: str = Field(default="")
    watch_uuid: Optional[str] = Field(default=None)
    type: str = Field(default="changedetection")
    enabled: bool = Field(default=True)
    keywords_critical: List[str] = Field(default_factory=list)
    keywords_watch: List[str] = Field(default_factory=list)


class HealthContext(BaseModel):
    """Agent context (Pydantic serialization)"""

    agency: Optional[str] = None
    source: Optional[str] = None  # New: more generic than agency
    source_type: Optional[SourceType] = None
    timestamp: datetime = Field(default_factory=datetime.now)
    webhook_id: Optional[str] = None
    report_mode: bool = False
    digest_mode: bool = False  # New: for digest generation
    execution_log: List[str] = Field(default_factory=list)
    statistics: dict = Field(default_factory=dict)
    current_disease: Optional[str] = None  # New: current disease being processed

    def log(self, message: str) -> None:
        """Log a message to execution log"""
        log_entry = f"[{datetime.now().isoformat()}] {message}"
        self.execution_log.append(log_entry)
        print(log_entry)


class DeduplicationResult(BaseModel):
    """Result of deduplication check"""

    is_duplicate: bool = Field(..., description="Whether this is a duplicate")
    existing_id: Optional[int] = Field(
        default=None, description="ID of existing record if duplicate"
    )
    existing_headline: Optional[str] = Field(
        default=None, description="Headline of existing record"
    )
    similarity_score: Optional[float] = Field(
        default=None, description="Similarity score (0-1)"
    )
    content_hash: str = Field(..., description="Hash of the content")


class TranslationRequest(BaseModel):
    """Request for Arabic translation"""

    text_en: str = Field(..., description="English text to translate")
    is_short_description: bool = Field(
        default=False,
        description="Whether this is a short description (affects formatting)",
    )
    disease_context: Optional[str] = Field(
        default=None, description="Disease name for context-aware translation"
    )


class TranslationResponse(BaseModel):
    """Response from translation"""

    text_ar: str = Field(..., description="Arabic translation")
    original_en: str = Field(..., description="Original English text")
    translation_quality: str = Field(
        default="standard",
        description="Quality indicator (standard, verified, reviewed)",
    )
