"""
Reclassify Workflow — SehaRadar v1.0

Scans NocoDB for findings with unidentified disease ("news", "Unknown", or empty)
and re-runs LLM-primary classification against their existing headline + description.
Updates the record in-place with the new disease name and priority.

Supports concurrent LLM classification via asyncio.Semaphore for throughput.
"""

import asyncio
import json
from datetime import datetime
from typing import Dict, Any, List, Optional

from tools.nocodb_client import NocoDBClientV3
from tools.epi_triad_analyzer import (
    EpidemiologicalTriad,
    epi_analyzer,
    determine_priority,
    add_disease_to_library,
    normalize_disease_name,
)
from tools.disease_catalog import add_discovered_disease, has_icon_metadata

# Sentinel values that mean "not yet classified"
UNCLASSIFIED_VALUES = {"news", "unknown", "unknown disease", "", None}

# Max concurrent LLM calls — gpt-4o-mini handles 500+ RPM;
# 5 concurrent keeps us well under while giving ~5x speedup.
_DEFAULT_CONCURRENCY = 5


async def _fetch_unclassified(
    nocodb: NocoDBClientV3, limit: int
) -> List[Dict[str, Any]]:
    """
    Fetch records whose disease field is an unclassified sentinel, paginating
    until `limit` records have been collected or the table is exhausted.
    """
    collected: List[Dict[str, Any]] = []
    offset = 0
    page_size = 100

    while len(collected) < limit:
        batch = await nocodb.query_findings(
            where="(disease,eq,news)~or(disease,eq,Unknown)~or(disease,eq,)~or(disease,blank)",
            limit=page_size,
            offset=offset,
            sort="-id",
        )
        if not batch:
            break

        for record in batch:
            disease_val = (record.get("disease") or "").strip().lower()
            if disease_val in UNCLASSIFIED_VALUES:
                collected.append(record)
                if len(collected) >= limit:
                    break

        if len(batch) < page_size:
            break  # last page
        offset += page_size

    return collected


async def _patch_record(
    nocodb: NocoDBClientV3,
    record_id: int,
    updates: Dict[str, Any],
) -> bool:
    """PATCH a single NocoDB record through the shared fallback client."""
    return await nocodb.patch_records([{"id": record_id, **updates}])


def _clean_template_description(description: str, headline: str) -> str:
    """
    Strip template/placeholder content from descriptions generated by previous
    failed LLM runs.  These contain boilerplate like '## Overview\\n<headline>'
    and 'Disease: Unknown Disease' which actively confuse the classifier.

    Returns the cleaned description, or empty string if nothing useful remains.
    """
    if not description:
        return ""

    template_markers = [
        "Disease: Unknown",
        "Disease: Not specified",
        "Location: Location not specified",
        "## Epidemiological Summary",
    ]

    is_template = description.strip().startswith("## Overview") and any(
        marker in description for marker in template_markers
    )

    if is_template:
        return ""

    desc_core = description.replace("## Overview", "").strip()
    if desc_core == headline.strip():
        return ""

    return description


async def _classify_single_record(
    record: Dict[str, Any],
    idx: int,
    total: int,
    nocodb: NocoDBClientV3,
    dry_run: bool,
    semaphore: asyncio.Semaphore,
) -> Dict[str, Any]:
    """
    Classify a single record under the concurrency semaphore.

    Returns:
        Result dict with id, old/new disease, patched status, and flags
        for identified/updated counts.
    """
    async with semaphore:
        record_id = record.get("id") or record.get("Id")
        if not record_id:
            print(f"  ⚠️ Skipping record with no id")
            return {"skipped": True}

        headline = record.get("headline", "")
        raw_description = (
            record.get("detailed_description_en", "")
            or record.get("short_description_en", "")
            or record.get("summary", "")
            or ""
        )

        description = _clean_template_description(raw_description, headline)
        source = record.get("source", "Unknown")

        print(f"\n  [{idx}/{total}] ID={record_id} | {headline[:60]}...")

        triad = EpidemiologicalTriad(
            who_affected="Unknown",
            where_location=record.get("location") or "Unknown",
        )

        try:
            (
                llm_disease,
                short_desc,
                detailed_desc,
                llm_keywords,
            ) = await epi_analyzer.classify_and_describe(
                headline=headline,
                description=description,
                source=source,
                triad=triad,
            )
        except Exception as e:
            print(f"    ❌ LLM error for record {record_id}: {e}")
            return {
                "id": record_id,
                "headline": headline[:80],
                "old_disease": record.get("disease"),
                "new_disease": None,
                "error": str(e),
                "patched": False,
                "_identified": False,
                "_updated": False,
            }

        new_disease = llm_disease

        # Normalize disease name to canonical form (e.g. "Nipah virus" → "Nipah")
        if new_disease and new_disease.lower() not in UNCLASSIFIED_VALUES:
            normalized = normalize_disease_name(new_disease)
            if normalized != new_disease:
                print(f"    📎 Normalized disease: '{new_disease}' → '{normalized}'")
                new_disease = normalized

        result_entry: Dict[str, Any] = {
            "id": record_id,
            "headline": headline[:80],
            "old_disease": record.get("disease"),
            "new_disease": new_disease,
            "_identified": False,
            "_updated": False,
        }

        if new_disease and new_disease.lower() not in UNCLASSIFIED_VALUES:
            # ── Disease identified ──────────────────────────────────────
            result_entry["_identified"] = True
            new_priority = determine_priority(
                new_disease,
                None,
                None,
                f"{headline} {description}",
            ).value

            result_entry["new_priority"] = new_priority
            print(f"    🦠 Identified: '{new_disease}' (priority: {new_priority})")

            add_disease_to_library(new_disease, llm_keywords)
            if not has_icon_metadata(new_disease):
                try:
                    await add_discovered_disease(new_disease)
                except Exception as catalog_err:
                    print(f"    ⚠️ Catalog error: {catalog_err}")

            if not dry_run:
                updates: Dict[str, Any] = {
                    "disease": new_disease,
                    "risk": new_priority,
                }
                if (
                    not record.get("short_description_en")
                    or len(record.get("short_description_en", "")) < 30
                ):
                    updates["short_description_en"] = short_desc
                if (
                    not record.get("detailed_description_en")
                    or len(record.get("detailed_description_en", "")) < 50
                ):
                    updates["detailed_description_en"] = detailed_desc

                patched = await _patch_record(nocodb, record_id, updates)
                if patched:
                    result_entry["_updated"] = True
                    result_entry["patched"] = True
                    print(f"    ✅ Updated record {record_id}")
                else:
                    result_entry["patched"] = False
            else:
                result_entry["patched"] = "dry_run"
        else:
            # ── Still unclassified — normalise to "news" ────────────────
            print(f"    ⚠️ LLM could not identify disease — updating to 'news'")
            result_entry["new_priority"] = None

            if not dry_run:
                old_disease = (record.get("disease") or "").strip().lower()
                if old_disease != "news":
                    patched = await _patch_record(
                        nocodb, record_id, {"disease": "news"}
                    )
                    if patched:
                        result_entry["_updated"] = True
                        result_entry["patched"] = True
                        print(f"    ✅ Updated record {record_id}: 'Unknown' → 'news'")
                    else:
                        result_entry["patched"] = False
                else:
                    result_entry["patched"] = False  # already "news", skip
            else:
                result_entry["patched"] = "dry_run"

        return result_entry


async def reclassify_unclassified(
    limit: int = 200,
    dry_run: bool = False,
    concurrency: int = _DEFAULT_CONCURRENCY,
) -> Dict[str, Any]:
    """
    Main entry point.  Finds unclassified DB records, re-runs LLM classification,
    and patches them with the correct disease name + priority.

    Processes records concurrently (default 5 at a time) for ~5x speedup over
    sequential processing.

    Args:
        limit:       Max number of records to process in this run.
        dry_run:     If True, classify but do NOT write back to NocoDB.
        concurrency: Max parallel LLM calls (default 5).

    Returns:
        Summary dict with counts and per-record results.
    """
    nocodb = NocoDBClientV3()
    start_time = datetime.now()

    print(
        f"\n🔬 Reclassify workflow started — limit={limit}, dry_run={dry_run}, "
        f"concurrency={concurrency}"
    )

    # 1. Fetch unclassified records
    records = await _fetch_unclassified(nocodb, limit)
    print(f"📋 Found {len(records)} unclassified records to process")

    if not records:
        return {
            "status": "ok",
            "message": "No unclassified records found",
            "processed": 0,
            "identified": 0,
            "still_unclassified": 0,
            "updated": 0,
            "dry_run": dry_run,
            "duration_seconds": 0,
        }

    # 2. Process records concurrently in batches with progress reporting
    semaphore = asyncio.Semaphore(concurrency)
    batch_size = 50  # progress report every 50 records
    all_results: List[Dict[str, Any]] = []
    identified_count = 0
    updated_count = 0

    for batch_start in range(0, len(records), batch_size):
        batch = records[batch_start : batch_start + batch_size]
        batch_end = batch_start + len(batch)

        print(
            f"\n{'─' * 60}"
            f"\n📦 Processing batch {batch_start + 1}–{batch_end} of {len(records)}"
            f"\n{'─' * 60}",
            flush=True,
        )

        tasks = [
            _classify_single_record(
                record=record,
                idx=batch_start + i + 1,
                total=len(records),
                nocodb=nocodb,
                dry_run=dry_run,
                semaphore=semaphore,
            )
            for i, record in enumerate(batch)
        ]

        batch_results = await asyncio.gather(*tasks, return_exceptions=True)

        for raw_result in batch_results:
            if isinstance(raw_result, BaseException):
                import traceback

                print(f"    ❌ Unexpected error: {raw_result}")
                traceback.print_exception(
                    type(raw_result), raw_result, raw_result.__traceback__
                )
                continue
            result: Dict[str, Any] = raw_result
            if result.get("skipped"):
                continue

            all_results.append(result)
            if result.get("_identified"):
                identified_count += 1
            if result.get("_updated"):
                updated_count += 1

        # Batch progress summary
        elapsed = (datetime.now() - start_time).total_seconds()
        processed_so_far = batch_end
        rate = processed_so_far / elapsed if elapsed > 0 else 0
        remaining = len(records) - processed_so_far
        eta_seconds = remaining / rate if rate > 0 else 0

        print(
            f"\n📊 Progress: {processed_so_far}/{len(records)} processed | "
            f"{identified_count} identified | {updated_count} updated | "
            f"{elapsed:.0f}s elapsed | ETA: {eta_seconds:.0f}s",
            flush=True,
        )

    duration = (datetime.now() - start_time).total_seconds()
    still_unclassified = len(records) - identified_count

    # Strip internal tracking keys from results
    clean_results = [
        {k: v for k, v in r.items() if not k.startswith("_")} for r in all_results
    ]

    summary = {
        "status": "ok",
        "processed": len(records),
        "identified": identified_count,
        "still_unclassified": still_unclassified,
        "updated": updated_count,
        "dry_run": dry_run,
        "concurrency": concurrency,
        "duration_seconds": round(duration, 1),
        "results": clean_results,
    }

    print(
        f"\n✅ Reclassify complete: {identified_count}/{len(records)} identified, "
        f"{updated_count} updated, {still_unclassified} still unclassified "
        f"({duration:.1f}s, concurrency={concurrency})"
    )

    return summary
