"""
Email Digest Tool for DabDar v3.0
Compiles and sends bilingual email digests via n8n webhook
"""

import os
import json
import httpx
from typing import List, Dict, Any, Optional
from datetime import datetime, timedelta
from agents import function_tool, RunContextWrapper
from health_agents.shared.models import HealthContext, DigestReport, Priority
from tools.nocodb_client import nocodb_v3


class EmailDigestService:
    """Service for compiling and sending email digests"""

    # Bilingual email template
    EMAIL_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }}
        .header {{ background: linear-gradient(135deg, #1a5276, #2980b9); color: white; padding: 20px; border-radius: 8px; margin-bottom: 20px; }}
        .header h1 {{ margin: 0; }}
        .stats {{ display: flex; gap: 15px; margin-top: 10px; flex-wrap: wrap; }}
        .stat {{ background: rgba(255,255,255,0.2); padding: 8px 15px; border-radius: 4px; }}
        .section {{ margin: 20px 0; padding: 15px; border-radius: 8px; }}
        .critical {{ background: #fdf2f2; border-left: 4px solid #e74c3c; }}
        .high {{ background: #fef9e7; border-left: 4px solid #f39c12; }}
        .medium {{ background: #eafaf1; border-left: 4px solid #27ae60; }}
        .finding {{ padding: 15px; margin: 10px 0; background: white; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }}
        .finding h3 {{ margin: 0 0 10px 0; color: #2c3e50; }}
        .finding-meta {{ font-size: 0.85em; color: #7f8c8d; margin-bottom: 10px; }}
        .priority-badge {{ display: inline-block; padding: 2px 8px; border-radius: 3px; font-size: 0.75em; font-weight: bold; text-transform: uppercase; }}
        .priority-critical {{ background: #e74c3c; color: white; }}
        .priority-high {{ background: #f39c12; color: white; }}
        .priority-medium {{ background: #27ae60; color: white; }}
        .priority-low {{ background: #95a5a6; color: white; }}
        .arabic {{ direction: rtl; text-align: right; font-family: 'Segoe UI', Tahoma, Arial, sans-serif; }}
        .divider {{ border-top: 2px solid #bdc3c7; margin: 40px 0; }}
        .footer {{ text-align: center; color: #7f8c8d; font-size: 0.85em; margin-top: 30px; }}
        a {{ color: #3498db; text-decoration: none; }}
        a:hover {{ text-decoration: underline; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>🌍 Disease Surveillance Digest</h1>
        <p><strong>Period:</strong> {period} | <strong>Generated:</strong> {generated_at}</p>
        <div class="stats">
            <div class="stat">📊 Total: {total_findings}</div>
            <div class="stat">🔴 Critical: {critical_count}</div>
            <div class="stat">🟠 High: {high_count}</div>
            <div class="stat">🟢 Medium: {medium_count}</div>
        </div>
    </div>
    
    {findings_html_en}
    
    <div class="divider"></div>
    
    <div class="arabic">
        <div class="header" style="text-align: right;">
            <h1>🌍 تقرير مراقبة الأمراض</h1>
            <p><strong>الفترة:</strong> {period_ar} | <strong>تاريخ الإنشاء:</strong> {generated_at}</p>
            <div class="stats" style="justify-content: flex-end;">
                <div class="stat">📊 الإجمالي: {total_findings}</div>
                <div class="stat">🔴 حرج: {critical_count}</div>
                <div class="stat">🟠 عالي: {high_count}</div>
                <div class="stat">🟢 متوسط: {medium_count}</div>
            </div>
        </div>
        
        {findings_html_ar}
    </div>
    
    <div class="footer">
        <p>Generated by DabDar v3.0 Health Surveillance System</p>
        <p>This is an automated report. Do not reply to this email.</p>
    </div>
</body>
</html>"""

    FINDING_TEMPLATE_EN = """
    <div class="finding">
        <h3>{headline}</h3>
        <div class="finding-meta">
            <span class="priority-badge priority-{priority}">{priority}</span>
            <strong>Disease:</strong> {disease} | 
            <strong>Source:</strong> {source} | 
            <strong>Date:</strong> {date}
        </div>
        <p>{short_description}</p>
        <a href="{link}">Read more →</a>
    </div>"""

    FINDING_TEMPLATE_AR = """
    <div class="finding">
        <h3>{headline}</h3>
        <div class="finding-meta">
            <span class="priority-badge priority-{priority}">{priority_ar}</span>
            <strong>المرض:</strong> {disease_ar} | 
            <strong>المصدر:</strong> {source} | 
            <strong>التاريخ:</strong> {date}
        </div>
        <p>{short_description_ar}</p>
        <a href="{link}">اقرأ المزيد ←</a>
    </div>"""

    PRIORITY_AR = {"critical": "حرج", "high": "عالي", "medium": "متوسط", "low": "منخفض"}

    PERIOD_AR = {"hourly": "كل ساعة", "6hours": "كل 6 ساعات", "daily": "يومي"}

    def __init__(self):
        self.n8n_webhook_url = os.getenv("N8N_DIGEST_WEBHOOK_URL", "")
        self.recipients = os.getenv("DIGEST_RECIPIENTS", "").split(",")
        self.digest_interval = os.getenv("DIGEST_INTERVAL", "daily")

    async def get_unsent_findings(self) -> List[Dict[str, Any]]:
        """Get all findings not yet included in a digest"""
        return await nocodb_v3.query_unsent_findings(limit=200)

    def group_by_priority(
        self, findings: List[Dict[str, Any]]
    ) -> Dict[str, List[Dict[str, Any]]]:
        """Group findings by priority level"""
        grouped = {"critical": [], "high": [], "medium": [], "low": []}

        for finding in findings:
            risk = finding.get("risk") or finding.get("priority", "medium")
            if risk in grouped:
                grouped[risk].append(finding)
            else:
                grouped["medium"].append(finding)

        return grouped

    def render_findings_html_en(
        self, grouped_findings: Dict[str, List[Dict[str, Any]]]
    ) -> str:
        """Render English findings HTML"""
        html = ""

        for priority, label in [
            ("critical", "🔴 Critical Alerts"),
            ("high", "🟠 High Priority"),
            ("medium", "🟢 Routine Updates"),
        ]:
            findings = grouped_findings.get(priority, [])
            if not findings:
                continue

            priority_class = priority
            html += f'<div class="section {priority_class}"><h2>{label} ({len(findings)})</h2>'

            for finding in findings:
                html += self.FINDING_TEMPLATE_EN.format(
                    headline=finding.get("headline", "No headline"),
                    priority=priority,
                    disease=finding.get("disease", "Unknown"),
                    source=finding.get("source", "Unknown"),
                    date=finding.get("publication_date", ""),
                    short_description=finding.get("short_description_en")
                    or finding.get("summary", "No description available."),
                    link=finding.get("source_link") or finding.get("url", "#"),
                )

            html += "</div>"

        return html

    def render_findings_html_ar(
        self, grouped_findings: Dict[str, List[Dict[str, Any]]]
    ) -> str:
        """Render Arabic findings HTML"""
        html = ""

        for priority, label in [
            ("critical", "🔴 تنبيهات حرجة"),
            ("high", "🟠 أولوية عالية"),
            ("medium", "🟢 تحديثات روتينية"),
        ]:
            findings = grouped_findings.get(priority, [])
            if not findings:
                continue

            html += (
                f'<div class="section {priority}"><h2>{label} ({len(findings)})</h2>'
            )

            for finding in findings:
                # Get Arabic disease name from config
                disease_ar = finding.get("disease", "غير معروف")

                html += self.FINDING_TEMPLATE_AR.format(
                    headline=finding.get("headline", "بدون عنوان"),
                    priority=priority,
                    priority_ar=self.PRIORITY_AR.get(priority, "متوسط"),
                    disease_ar=disease_ar,
                    source=finding.get("source", "Unknown"),
                    date=finding.get("publication_date", ""),
                    short_description_ar=finding.get("short_description_ar")
                    or finding.get("short_description_en", "لا يوجد وصف متاح."),
                    link=finding.get("source_link") or finding.get("url", "#"),
                )

            html += "</div>"

        return html

    async def compile_digest(self, interval: str = None) -> DigestReport:
        """
        Compile email digest from unsent findings.

        Args:
            interval: Digest interval (hourly, 6hours, daily)

        Returns:
            DigestReport object
        """
        interval = interval or self.digest_interval

        # Get unsent findings
        findings = await self.get_unsent_findings()

        if not findings:
            return DigestReport(
                digest_id=f"digest_{datetime.now().strftime('%Y%m%d_%H%M%S')}",
                period=interval,
                period_start=(datetime.now() - timedelta(hours=24)).isoformat(),
                period_end=datetime.now().isoformat(),
                total_findings=0,
                findings=[],
                html_content_en="<p>No new findings to report.</p>",
                html_content_ar="<p>لا توجد نتائج جديدة للإبلاغ عنها.</p>",
            )

        # Group by priority
        grouped = self.group_by_priority(findings)

        # Count by priority
        critical_count = len(grouped["critical"])
        high_count = len(grouped["high"])
        medium_count = len(grouped["medium"])
        low_count = len(grouped["low"])

        # Render HTML
        findings_html_en = self.render_findings_html_en(grouped)
        findings_html_ar = self.render_findings_html_ar(grouped)

        # Build full email HTML
        full_html = self.EMAIL_TEMPLATE.format(
            period=interval.capitalize(),
            period_ar=self.PERIOD_AR.get(interval, "يومي"),
            generated_at=datetime.now().strftime("%Y-%m-%d %H:%M"),
            total_findings=len(findings),
            critical_count=critical_count,
            high_count=high_count,
            medium_count=medium_count,
            findings_html_en=findings_html_en,
            findings_html_ar=findings_html_ar,
        )

        return DigestReport(
            digest_id=f"digest_{datetime.now().strftime('%Y%m%d_%H%M%S')}",
            period=interval,
            period_start=(datetime.now() - timedelta(hours=24)).isoformat(),
            period_end=datetime.now().isoformat(),
            total_findings=len(findings),
            critical_count=critical_count,
            high_count=high_count,
            medium_count=medium_count,
            low_count=low_count,
            findings=findings,
            html_content_en=full_html,
            html_content_ar=findings_html_ar,
            recipients=self.recipients,
        )

    async def send_to_n8n(self, digest: DigestReport) -> bool:
        """
        Send digest to n8n webhook for email delivery.

        Args:
            digest: Compiled digest report

        Returns:
            True if successful
        """
        if not self.n8n_webhook_url:
            print("⚠️ N8N_DIGEST_WEBHOOK_URL not configured")
            return False

        payload = {
            "digest_id": digest.digest_id,
            "period": digest.period,
            "total_findings": digest.total_findings,
            "critical_count": digest.critical_count,
            "high_count": digest.high_count,
            "medium_count": digest.medium_count,
            "html_content": digest.html_content_en,
            "recipients": digest.recipients,
            "generated_at": datetime.now().isoformat(),
        }

        try:
            async with httpx.AsyncClient(timeout=60.0) as client:
                response = await client.post(
                    self.n8n_webhook_url,
                    json=payload,
                    headers={"Content-Type": "application/json"},
                )
                response.raise_for_status()
                return True
        except Exception as e:
            print(f"❌ Error sending to n8n: {e}")
            return False

    async def mark_findings_sent(self, findings: List[Dict[str, Any]]) -> bool:
        """Mark all findings in digest as sent"""
        record_ids = [
            f.get("Id") or f.get("id") for f in findings if f.get("Id") or f.get("id")
        ]
        if record_ids:
            return await nocodb_v3.mark_as_sent(record_ids)
        return True


# Global service instance
digest_service = EmailDigestService()


@function_tool
async def compile_email_digest(
    ctx: RunContextWrapper[HealthContext], interval: str = "daily"
) -> str:
    """
    Compile email digest from unsent findings.

    Args:
        interval: Digest interval (hourly, 6hours, daily)

    Returns:
        JSON string with digest report including HTML content
    """
    ctx.context.log(f"📧 Compiling {interval} email digest...")

    digest = await digest_service.compile_digest(interval)

    ctx.context.log(
        f"✅ Digest compiled: {digest.total_findings} findings ({digest.critical_count} critical, {digest.high_count} high)"
    )

    # Return simplified version (without full findings list for message size)
    result = {
        "digest_id": digest.digest_id,
        "period": digest.period,
        "total_findings": digest.total_findings,
        "critical_count": digest.critical_count,
        "high_count": digest.high_count,
        "medium_count": digest.medium_count,
        "low_count": digest.low_count,
        "html_preview": digest.html_content_en[:1000] + "..."
        if len(digest.html_content_en) > 1000
        else digest.html_content_en,
        "recipients": digest.recipients,
    }

    return json.dumps(result, ensure_ascii=False)


@function_tool
async def send_digest_email(
    ctx: RunContextWrapper[HealthContext], interval: str = "daily"
) -> str:
    """
    Compile and send email digest via n8n.

    Args:
        interval: Digest interval (hourly, 6hours, daily)

    Returns:
        Status message
    """
    ctx.context.log(f"📧 Preparing {interval} digest for sending...")

    # Compile
    digest = await digest_service.compile_digest(interval)

    if digest.total_findings == 0:
        ctx.context.log("ℹ️ No findings to send")
        return "No new findings to send in digest"

    ctx.context.log(f"📤 Sending digest to n8n ({digest.total_findings} findings)...")

    # Send to n8n
    success = await digest_service.send_to_n8n(digest)

    if success:
        # Mark as sent
        await digest_service.mark_findings_sent(digest.findings)
        ctx.context.log(
            f"✅ Digest sent successfully to {len(digest.recipients)} recipients"
        )
        return f"Digest sent successfully: {digest.total_findings} findings to {len(digest.recipients)} recipients"
    else:
        ctx.context.log("❌ Failed to send digest")
        return "Failed to send digest via n8n"


@function_tool
async def preview_digest(ctx: RunContextWrapper[HealthContext]) -> str:
    """
    Preview the next digest without sending.

    Returns:
        JSON with digest preview
    """
    ctx.context.log("👁️ Previewing next digest...")

    digest = await digest_service.compile_digest()

    # Get summary
    summary = {
        "total_findings": digest.total_findings,
        "critical_count": digest.critical_count,
        "high_count": digest.high_count,
        "medium_count": digest.medium_count,
        "low_count": digest.low_count,
        "period": digest.period,
        "would_send_to": digest.recipients,
    }

    ctx.context.log(f"✅ Preview: {digest.total_findings} findings would be included")

    return json.dumps(summary)
