#!/usr/bin/env node
import { mkdtempSync, writeFileSync, rmSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { spawnSync } from 'node:child_process';

const USAGE = `Usage:
  node cloudflare/scripts/seed-sources.mjs --print
  node cloudflare/scripts/seed-sources.mjs --mvp --print
  node cloudflare/scripts/seed-sources.mjs --database seharadar-prod [--local|--remote]

Options:
  --config <path>       Source registry path. Defaults to config/sources.json.
  --database <name>     D1 database name or binding accepted by wrangler d1 execute.
  --mvp                 Enable only the Cloudflare MVP sources: WHO, CDC, ECDC.
  --local               Execute against local D1.
  --remote              Execute against remote D1.
  --print               Print generated SQL instead of executing wrangler.
  --dry-run             Alias for --print.
  --help                Show this help.
`;

const args = parseArgs(process.argv.slice(2));

if (args.help) {
  console.log(USAGE);
  process.exit(0);
}

if (!args.print && !args.database) {
  console.error('Missing required --database unless --print is used.');
  console.error(USAGE);
  process.exit(1);
}

if (args.local && args.remote) {
  console.error('Use only one of --local or --remote.');
  process.exit(1);
}

const configPath = resolve(process.cwd(), args.config ?? 'config/sources.json');
const sourceConfig = JSON.parse(await readFile(configPath, 'utf8'));

if (!Array.isArray(sourceConfig.sources)) {
  throw new Error(`${configPath} must contain a sources array`);
}

const now = new Date().toISOString();
const enabledSourceIds = args.mvp ? new Set(['WHO', 'CDC', 'ECDC']) : null;
const sql = buildSeedSql(sourceConfig.sources, now, enabledSourceIds);

if (args.print) {
  process.stdout.write(sql);
  process.exit(0);
}

const tempDir = mkdtempSync(join(tmpdir(), 'seharadar-source-seed-'));
const sqlPath = join(tempDir, 'seed-sources.sql');

try {
  writeFileSync(sqlPath, sql, 'utf8');

  const wranglerArgs = ['wrangler', 'd1', 'execute', args.database, '--file', sqlPath];
  if (args.remote) wranglerArgs.push('--remote');
  if (args.local) wranglerArgs.push('--local');

  const result = spawnSync('npx', wranglerArgs, {
    cwd: process.cwd(),
    stdio: 'inherit',
  });

  if (result.error) throw result.error;
  process.exit(result.status ?? 1);
} finally {
  rmSync(tempDir, { recursive: true, force: true });
}

function parseArgs(argv) {
  const parsed = {};

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];

    if (arg === '--help' || arg === '-h') parsed.help = true;
    else if (arg === '--print' || arg === '--dry-run') parsed.print = true;
    else if (arg === '--mvp') parsed.mvp = true;
    else if (arg === '--local') parsed.local = true;
    else if (arg === '--remote') parsed.remote = true;
    else if (arg === '--database' || arg === '--config') {
      const value = argv[index + 1];
      if (!value || value.startsWith('--')) {
        throw new Error(`${arg} requires a value`);
      }
      parsed[arg.slice(2)] = value;
      index += 1;
    } else {
      throw new Error(`Unknown argument: ${arg}`);
    }
  }

  return parsed;
}

function buildSeedSql(sources, now, enabledSourceIds = null) {
  const statements = [
    '-- Generated by cloudflare/scripts/seed-sources.mjs. Do not hand-edit before review.',
  ];

  for (const source of sources) {
    validateSource(source);

    const checkIntervalSeconds = checkIntervalToSeconds(source.check_interval);
    const tagsJson = JSON.stringify(source.tags ?? []);
    const configJson = JSON.stringify(buildConfigJson(source));
    const enabled = source.enabled === false || (enabledSourceIds && !enabledSourceIds.has(source.id)) ? 0 : 1;
    const nextCheckAt = enabled ? now : null;

    statements.push(`insert into sources (
  id,
  name,
  type,
  url,
  parser,
  enabled,
  check_interval_seconds,
  priority_boost,
  tags_json,
  config_json,
  legacy_watch_uuid,
  created_at,
  updated_at
) values (
  ${sqlString(source.id)},
  ${sqlString(source.name)},
  ${sqlString(source.type)},
  ${sqlString(source.url ?? null)},
  ${sqlString(source.parser ?? null)},
  ${enabled},
  ${checkIntervalSeconds},
  ${Number.isInteger(source.priority_boost) ? source.priority_boost : 0},
  ${sqlString(tagsJson)},
  ${sqlString(configJson)},
  ${sqlString(source.watch_uuid ?? null)},
  ${sqlString(now)},
  ${sqlString(now)}
) on conflict(id) do update set
  name = excluded.name,
  type = excluded.type,
  url = excluded.url,
  parser = excluded.parser,
  enabled = excluded.enabled,
  check_interval_seconds = excluded.check_interval_seconds,
  priority_boost = excluded.priority_boost,
  tags_json = excluded.tags_json,
  config_json = excluded.config_json,
  legacy_watch_uuid = excluded.legacy_watch_uuid,
  updated_at = excluded.updated_at;`);

    statements.push(`insert into source_state (
  source_id,
  next_check_at,
  consecutive_failures
) values (
  ${sqlString(source.id)},
  ${sqlString(nextCheckAt)},
  0
) on conflict(source_id) do update set
  source_id = excluded.source_id;`);
  }

  statements.push('');
  return statements.join('\n\n');
}

function validateSource(source) {
  for (const field of ['id', 'name', 'type']) {
    if (typeof source[field] !== 'string' || source[field].length === 0) {
      throw new Error(`Source is missing required string field: ${field}`);
    }
  }
}

function checkIntervalToSeconds(interval) {
  if (!interval || typeof interval !== 'object') return 3600;

  const units = {
    days: 86400,
    hours: 3600,
    minutes: 60,
    seconds: 1,
  };

  let total = 0;
  for (const [unit, multiplier] of Object.entries(units)) {
    const value = interval[unit] ?? 0;
    if (!Number.isFinite(value) || value < 0) {
      throw new Error(`Invalid check_interval.${unit}: ${value}`);
    }
    total += value * multiplier;
  }

  return Math.max(1, Math.trunc(total || 3600));
}

function buildConfigJson(source) {
  const config = { ...(source.config ?? {}) };

  for (const [key, value] of Object.entries(source)) {
    if (![
      'id',
      'name',
      'type',
      'watch_uuid',
      'url',
      'parser',
      'check_interval',
      'enabled',
      'priority_boost',
      'tags',
      'config',
    ].includes(key)) {
      config[key] = value;
    }
  }

  return config;
}

function sqlString(value) {
  if (value === null || value === undefined) return 'null';
  return `'${String(value).replaceAll("'", "''")}'`;
}
